version: 0.2

phases:
  install:
    runtime-versions:
      php: 7.4 # Change this to your desired PHP version
  pre_build:
    commands:
      - echo "Installing dependencies..."
      # Add any pre-build commands you may need here
  build:
    commands:
      - echo "Building WordPress application..."
      - wget https://wordpress.org/latest.tar.gz
      - tar -zxvf latest.tar.gz
      - cp -R wordpress/* .
      - rm -rf wordpress latest.tar.gz
      # Add any additional build commands you may need here
  post_build:
    commands:
      - echo "Post build steps..."
      # Add any post-build steps you may need here
artifacts:
  files:
    - '**/*'
